### ISSUE TITLE
[Bug] macosx_11_0_arm64.whl only contains an x86 lib

### ISSUE THREAD

**Issue by nihilox** [eclipse-zenoh/zenoh-python#60] opened 2022-04-21 07:03 UTC
### Describe the bug

`eclipse_zenoh-0.5.0b9-cp36-abi3-macosx_11_0_arm64.whl`

```bash
file zenoh.abi3.so
zenoh.abi3.so: Mach-O 64-bit dynamically linked shared library x86_64
```

### To reproduce

```
curl https://files.pythonhosted.org/packages/52/23/ccc52eeb84d6e8eef254682c19173467bf4b836021f2fbe3e6a42e29d603/eclipse_zenoh-0.5.0b9-cp36-abi3-macosx_11_0_arm64.whl
```

### System info

Darwin 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64

**Comment by JEnoch** [comment] 2022-04-21 09:36
You're right! It looks like something went wrong which this wheel when releasing 0.5.0b9.
Strangely, the universal2 wheel correctly contains a lib build for both arm64 and x86_64:

```bash
> wget https://files.pythonhosted.org/packages/b6/f2/17c768470fea6dbb750ed2e75383316a823353572f001bf9017dc2ca999f/eclipse_zenoh-0.5.0b9-cp36-abi3-macosx_10_9_universal2.whl
> unzip eclipse_zenoh-0.5.0b9-cp36-abi3-macosx_10_9_universal2.whl
> file zenoh.abi3.so
zenoh.abi3.so: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64Mach-O 64-bit dynamically linked shared library x86_64] [arm64]
zenoh.abi3.so (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
zenoh.abi3.so (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```

Anyway, the issue is fixed in the current CI, as you can see in the result of nightly builds here: https://pypi.org/project/eclipse-zenoh-nightly/

```bash
> wget wget https://files.pythonhosted.org/packages/d0/83/53324b45d22f48fdd56a6e99cec4bba925e5fa1d058422ca513714a9beaf/eclipse_zenoh_nightly-0.6.0.dev20220421-cp36-abi3-macosx_11_0_arm64.whl
> unzip eclipse_zenoh_nightly-0.6.0.dev20220421-cp36-abi3-macosx_11_0_arm64.whl
> file zenoh.abi3.so
zenoh.abi3.so: Mach-O 64-bit dynamically linked shared library arm64
```

You should rather use this nightly build, since the examples currently provided in the master branch are working with it, but won't work with the 0.5.0b9 version.

**Closed by JEnoch** 2022-04-21 09:36 UTC
Labels: bug
